# Generated by Django 3.2.11 on 2022-02-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Intake', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Track', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('intake_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.intake')),
                ('track_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.track')),
            ],
        ),
    ]
